In [3]:
import time
x=range(100000)
y=range(100000,200000)
start_time =time.time()
c = [x+y for x,y in zip(x,y)]
print(time.time() - start_time)

0.011425971984863281


In [5]:
import numpy as np
a= np.arange(100000)
b=np.arange(100000,200000)
start_time =time.time()
c=a+b
print(time.time()-start_time)

0.0038695335388183594


In [34]:
arr2=np.arange(30).reshape(6,5)
arr2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [16]:
arr2[3:]
# will print the row 3 and onwards

array([[15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [14]:
# arr2[2] will print row 2(10,11,12,13,14)
arr2[ :2]
# will print first two rows

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [25]:
arr2[: ,2:6]
# will print column 2  and  : means column two exists in all rows so it will print all rows can be written as arr2[0:,2] same output

array([[ 2,  3,  4],
       [ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19],
       [22, 23, 24],
       [27, 28, 29]])

In [52]:
# if we desire to print 18,19,23,24 then
arr2[3:5,3:5]
# will print our desired numbers 12,13,17,18

array([[18, 19],
       [23, 24]])